language: node_js
node_js:
  - "0.10"

before_install:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


branches:
  only:
    - travis
script:
- ./node_modules/karma/bin/karma start --single-run
